global:
  scrape_interval: 1m

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    scrape_interval: 20s
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "grafana"
    static_configs:
    - targets: ["grafana:3000"]

  - job_name: "alertmanager"
    static_configs:
    - targets: ["alertmanager:9093"]

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.google.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

### grafana/prometheus cloud config
#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"
